# Copyright 2025 Code17 GmbH
#
# This file is licensed under the Elastic License 2.0 (ELv2).
# Refer to the LICENSE.txt file in the root of the repository
# for details.
#

[env]
_.path = [
    "scripts"
]
_.python.venv = "src/python-api/.venv"

UV_PROJECT = "{{ config_root }}/src/python-api"

[tools]
"pipx:hatch" = "latest"
uv = "latest"
