# copyright 2022 the sqlnet company gmbh
#
# this file is licensed under the elastic license 2.0 (elv2).
# refer to the license.txt file in the root of the repository
# for details.
#

[project]
name = "getml"
description = "Python API for getML"
dynamic = ["version"]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "Elastic License 2.0 (ELv2)"}
authors = [{name="getML", email="getml@getml.com"},]
keywords = ["AutoML", "feature learning", "feature engineering"]
classifiers = [
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
    "Intended Audience :: Education",
    "Intended Audience :: Science/Research",
    "Intended Audience :: Financial and Insurance Industry",
    "Intended Audience :: Telecommunications Industry",
    "Intended Audience :: Information Technology",
    "Intended Audience :: Manufacturing",
    "Intended Audience :: Healthcare Industry",
    "Operating System :: OS Independent",
]
dependencies = [
    "pandas",
    "pyarrow>=11.0,<11.1",
    "numpy>=1.22",
    "jinja2",
    "scipy",
]

[project.urls]
"Hompage" = "https://getml.com"
"Documentation" = "https://docs.getml.com/latest"
"Bug Tracker" = "https://github.com/getml/getml-community/issues"
"Download" = "https://getml.com/product/download/"
"Source Code" = "https://github.com/getml/getml-community"

[project.optional-dependencies]
test = ["pytest", "pyspark"]
development = ["pyright", "ruff==0.4.5"]

[tool.setuptools]
packages = [
    "getml",
    "getml.data",
    "getml.data.columns",
    "getml.data.split",
    "getml.data.subroles",
    "getml.database",
    "getml.datasets",
    "getml.engine",
    "getml.feature_learning",
    "getml.hyperopt",
    "getml.pipeline",
    "getml.pipeline",
    "getml.predictors",
    "getml.preprocessors",
    "getml.project",
    "getml.project.containers",
    "getml.sqlite3",
    "getml.utilities",
    "getml.utilities.formatting",
    "getml.utilities.templates"
]

[tool.setuptools.dynamic]
version = {attr = "getml.version.__version__"}

[tool.setuptools.package-data]
getml = [
    "VERSION",
    "py.typed",
    "utilities/templates/*.jinja2",
    ".getML/**/*",
]

[tool.ruff.lint]
ignore = [
  # Allow over
  "A003",
  # Allow non-abstract empty methods in abstract base classes
  "B027",
  # Allow for string literals in exceptions
  "EM",
  # Allow boolean positional values in function calls, like `dict.get(... True)`
  "FBT003",
  # Ignore checks for possible passwords
  "S105", "S106", "S107",
  # Ignore complexity
  "C901", "PLR0911", "PLR0912", "PLR0913", "PLR0915",
]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"
